var autotyper = new AutoTyper();
autotyper.setListener((text) => {
  document.getElementById('textview').innerHTML = text;
});

autotyper.setHesitationFactor(.4);
autotyper.setMistypingFactor(.02);
autotyper.type( 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in dictum erat. Fusce volutpat porta ligula vel faucibus. Mauris tempor ipsum mi, ac tempus sapien venenatis et. Aliquam erat volutpat. Maecenas facilisis ac lectus sed sollicitudin. Praesent dapibus bibendum ipsum nec tincidunt. Duis sed nisl ex. Etiam ultricies tellus non leo feugiat interdum. In purus sem, posuere sed congue a, congue vitae ipsum. Phasellus id semper quam, vel volutpat est. Maecenas mollis ornare tempus. Nulla sodales porta nisi sit amet scelerisque. Nam id nibh massa. Donec tempor vestibulum lorem ac sollicitudin.\n' +
                'Ut justo nisl, vestibulum eget venenatis ultricies, commodo ut dui. Aliquam erat volutpat. In at consequat urna. Etiam mattis hendrerit felis, ac vulputate elit pharetra vel. Maecenas iaculis venenatis risus, ut sagittis ipsum vehicula non. Ut quis mattis augue. Nam ultricies mi non nisl maximus dignissim. In tristique placerat ex sed blandit. Nullam ullamcorper justo vitae justo ultricies, sit amet fermentum eros aliquet. Nullam et neque magna. Maecenas imperdiet cursus arcu ac lobortis. Phasellus ornare est ut urna mollis gravida. Aenean a nisl gravida, fermentum dui sit amet, semper felis. Aliquam semper sed purus ac sagittis.\n' +
                'Praesent non vulputate risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris vehicula nisl ut arcu venenatis faucibus. Aenean interdum elit diam, a tempus nisl lacinia vitae. Nulla faucibus odio ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque imperdiet mauris pretium risus tincidunt, eu tincidunt metus egestas. Sed tincidunt euismod orci, at imperdiet magna sagittis eu. Praesent sem quam, vehicula vitae magna vitae, luctus maximus ipsum. Donec et fermentum purus, convallis finibus leo.\n' +
                'Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam dictum pharetra ex, nec maximus eros dignissim in. Vivamus in tellus dapibus, ultrices lacus nec, pharetra nibh. Ut non porttitor leo, ac vehicula turpis. Nullam malesuada tristique aliquam. Integer vulputate iaculis placerat. Nulla viverra nibh at facilisis sagittis. Vivamus at nibh eros. Vivamus consequat eros eget ante malesuada, vel venenatis felis vulputate. Nam sed augue luctus ex dignissim convallis. Nunc purus arcu, dapibus et libero ac, viverra sagittis velit. Quisque aliquet ligula lorem, ultrices rhoncus lorem pellentesque quis. Nullam pulvinar metus sed neque lacinia, vel fermentum mauris vestibulum. Suspendisse in mauris dignissim, condimentum neque a, molestie urna.\n' +
                'Curabitur mauris enim, laoreet eu dapibus vitae, efficitur sodales erat. Aliquam vel sapien placerat, scelerisque dui eu, lobortis velit. Integer semper felis nisi, at sollicitudin enim dictum mollis. Morbi a lectus nulla. Etiam fermentum porttitor turpis eget scelerisque. Nam enim lorem, auctor nec pharetra non, varius eget dui. Morbi faucibus at justo id semper.');  